### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/home/kartik/Downloads/RE_CNN-master/data_processed/data_aligned.pkl'

### ISSUE THREAD

**Issue by kdhiwar** [hxy8149989/RE_CNN#1]
just trying your code to run very newbie to machine learning..getting error to create .pkl file..
can you tell the steps to run whole code in my my machine what changes should i do ? how to get these files

 data_file = "dataset\\SemEval2010_task8_all_data\\all_data.txt"
    data_cleared_file = "data_processed\\data_cleared.pkl"
    data_processed_file = "data_processed\\data_processed.pkl"
    data_aligned_file = "data_processed\\data_aligned.pkl"
    list_vocabulary_file = "tmp_files\\list_vocabulary.pkl"
    list_relation_file = "tmp_files\\list_relation.pkl"
    dict_vocabulary_file = "tmp_files\\dict_vocabulary.pkl"
    dict_relation_file = "tmp_files\\dict_relation.pkl"
    dict_wordvec_file = "tmp_files\\dict_wordvec.pkl"
    dict_posvec_file = "tmp_files\\dict_posvec.pkl"
    matrix_word_index_file = "tmp_files\\matrix_wordidx.pkl"
    matrix_pos_index_file = "tmp_files\\matrix_posidx.pkl"

**Comment by hxy8149989** [comment]
To generate these files you need to do 3 things.
1. I haven't uploaded the SE2010_task8_dataset, so you need to get it first.
2. Get the wordvec and use word2vec_mongodb.py to save them in mongodb, it means that you must have mongodb.
3. Create data_processed and tmp_files folders, all files in theses 2 folders are generated by process_data.py. And you may change the parameters to get these files.

**Comment by kdhiwar** [comment]
yes i had installed all dependencies and mongodb.having all dataset and scorer.I created data_processed,res_analysis and tmp_files folder...
located the file in word2vec_mongo.py
wordvec_file = "/home/kartik/Downloads/GloVe-1.2/glove.6B/glove.6B.50d.txt"

It run for 8 hours giving this-
![pjimage](https://cloud.githubusercontent.com/assets/19854742/16293139/00861b12-3935-11e6-8bac-d9ace6e54fc8.jpg)



then checked database in mongodb
 > show dbs
local	0.078125GB
wordvec	0.953125GB

-------------------then for running process_data.py

i simply merge train.txt and train.txt to create all_data.txt and loacate the file.
``
data_file = "/home/kartik/Downloads/RE_CNN-master/dataset/SemEval2010_task8_all_data/all_data.txt"
    data_cleared_file = "/home/kartik/Downloads/RE_CNN-master/data_processed/data_cleared.pkl"
    data_processed_file = "/home/kartik/Downloads/RE_CNN-master/data_processed/data_processed.pkl"
    data_aligned_file = "/home/kartik/Downloads/RE_CNN-master/data_processed/data_aligned.pkl"
    list_vocabulary_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/list_vocabulary.pkl"
    list_relation_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/list_relation.pkl"
    dict_vocabulary_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/dict_vocabulary.pkl"
    dict_relation_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/dict_relation.pkl"
    dict_wordvec_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/dict_wordvec.pkl"
    dict_posvec_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/dict_posvec.pkl"
    matrix_word_index_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/matrix_wordidx.pkl"
    matrix_pos_index_file = "/home/kartik/Downloads/RE_CNN-master/tmp_files/matrix_posidx.pkl"
``
getting following error-

![screenshot from 2016-06-23 10 57 55-1](https://cloud.githubusercontent.com/assets/19854742/16293796/4cbc9d44-393a-11e6-91fa-1c8c563c7fda.png)
